-- ============================================================
-- 03 — EXERCISES (exercices musculation par défaut)
-- ============================================================

INSERT INTO exercises (name, muscle_group, is_default, usage_count) VALUES
  ('Développé couché',        'pectoraux', true, 48),
  ('Développé incliné',       'pectoraux', true, 22),
  ('Développé décliné',       'pectoraux', true,  8),
  ('Écarté',                  'pectoraux', true, 12),
  ('Pompes',                  'pectoraux', true, 18),
  ('Dips',                    'pectoraux', true, 15),
  ('Pull-over',               'pectoraux', true,  7),
  ('Tractions',               'dos',       true, 30),
  ('Rowing barre',            'dos',       true, 38),
  ('Rowing haltère',          'dos',       true, 20),
  ('Tirage vertical',         'dos',       true, 28),
  ('Tirage horizontal',       'dos',       true, 22),
  ('Soulevé de terre',        'dos',       true, 45),
  ('Face pull',               'dos',       true, 15),
  ('Squat',                   'jambes',    true, 52),
  ('Front squat',             'jambes',    true, 12),
  ('Presse à cuisses',        'jambes',    true, 26),
  ('Leg curl',                'jambes',    true, 20),
  ('Leg extension',           'jambes',    true, 18),
  ('Fentes',                  'jambes',    true, 22),
  ('Bulgarian split squat',   'jambes',    true, 10),
  ('Mollets debout',          'jambes',    true, 15),
  ('Mollets assis',           'jambes',    true, 10),
  ('Développé militaire',     'epaules',   true, 32),
  ('Développé Arnold',        'epaules',   true, 12),
  ('Élévations latérales',    'epaules',   true, 28),
  ('Élévations frontales',    'epaules',   true, 10),
  ('Oiseau',                  'epaules',   true,  8),
  ('Rowing menton',           'epaules',   true, 12),
  ('Curl barre',              'biceps',    true, 32),
  ('Curl haltères',           'biceps',    true, 28),
  ('Curl marteau',            'biceps',    true, 20),
  ('Curl pupitre',            'biceps',    true, 15),
  ('Curl concentration',      'biceps',    true, 10),
  ('Dips triceps',            'triceps',   true, 20),
  ('Extensions nuque',        'triceps',   true, 18),
  ('Extensions poulie haute', 'triceps',   true, 22),
  ('Kickback',                'triceps',   true, 12),
  ('Barre au front',          'triceps',   true, 15),
  ('Crunch',                  'abdos',     true, 20),
  ('Planche',                 'abdos',     true, 18),
  ('Relevé de jambes',        'abdos',     true, 15),
  ('Russian twist',           'abdos',     true, 12),
  ('Mountain climbers',       'abdos',     true, 10),
  ('Bicycle crunch',          'abdos',     true,  8)
ON CONFLICT DO NOTHING;
